### ISSUE TITLE
Options object as a third parameter

### ISSUE THREAD

**Issue by akselinurmio** [lucacasonato/proposal-string-prototype-splitn#1]
As an addition to the current signatures in the Q&A section: would it be feasible to also consider options object as an extra parameter to the current `.split`?

```js
"a;b;c;d".split(";", 2, { remainder: true })
// ["a", "b;c;d"]
```

This would make it easy to have backward compatibility with the current specification, and also be verbose at the same time.

Extra parameter as an object is also a future proof method as it allows more options to be added if needed. It doesn't require a new function to be added and the same scheme has been used in the `EventTarget.addEventListener()` you mention in the proposal.

**Comment by mindplay-dk** [comment]
This doesn't seem like a good idea - feature detection for this option is going to be ugly and polyfilling will require an override, affecting perf of the original method.

That, and I'm pretty sure the old method will happily accept the new option without complaint and silently do the wrong thing, right?

Keep it simple, just add a new method.

**Comment by akselinurmio** [comment]
> This doesn't seem like a good idea - feature detection for this option is going to be ugly and polyfilling will require an override, affecting perf of the original method.

You're absolutely correct. Having slept over it, I think a new method is the way to go.

**Comment by lucacasonato** [comment]
I am going to add this to the FAQ anyway as an option, so we don't get another issue about it. But indeed unlikely that this is the path forward.
