### ISSUE TITLE
python has a green check but doesn't match the others

### ISSUE THREAD

**Issue by ljharb** [lucacasonato/proposal-string-prototype-splitn#2]
In your table, python doesn't return `['a', 'b|c|d|e|f']`, it returns `['a', 'b', 'c|d|e|f']`.

**Comment by lucacasonato** [comment]
This is why the green check is surrounded by braces :-)

**Comment by ljharb** [comment]
ah, parens is a pretty subtle indicator in a table where color and icon are the primary signals :-) maybe make it yellow?

**Comment by lucacasonato** [comment]
Yup, sounds good.

**Comment by lucacasonato** [comment]
Checkmark has been made orange in 533d87ea0c6200244034bd7b120bf97681afb775
