### ISSUE TITLE
N seems off for most languages in the table

### ISSUE THREAD

**Issue by ljharb** [lucacasonato/proposal-string-prototype-splitn#3]
> In most other languages splitN instead splits the original string N amount of times

When passing `2`, i'd thus expect two separators to be consumed - ie, Python's results. However, every other language in your table only consumes 1 separator.

It seems to me like Python and JavaScript are the *only* ones doing the intuitive thing to me, they just disagree about what to do with the remainder of the string.

(obviously another mental model could be, "2 means i want 2 parts", but in that case, #2 means it should be a red x, and JS could be green because it gives you two parts)

**Comment by lucacasonato** [comment]
You are right - all languages (except JS and Python) do N-1 splits, but return N items, whereas JS does N splits and returns N items. I will update the text.

**Comment by lucacasonato** [comment]
Ok, updated in fe267ad2904f55c801be96c86ec5ed90bf259a12. I have also added some more motivation text to explain why the other behaviour is often preferable.

**Comment by lucacasonato** [comment]
Note: additional fix in 8a801fe22f03488e73632d7df6a4ead7fedec1ba. I misunderstood Java's behaviour in my previous patch.
